### ISSUE TITLE
I dont get the keys and cant park

### ISSUE THREAD

**Issue by Aappoo69** [JonasDev17/qb-garages#100]
I imported radial menu, core and garages script at the latest version into my server. I see the script, but the problem is when i take my car out, it doesn`t give me the key of the car and also i cant park into any of the garage after i take my car out.

I get this script failure after i take my car out that already been in the garage from the other script, (Thats when i dont get the keys from the car)
![Proof](https://user-images.githubusercontent.com/104938883/222766654-a23ff353-89fa-4acb-8290-1abd182c640a.png)

Please help!!! im trying to fix this hours long

**Comment by BrandonSnippets** [comment]
Are you using a different fuel script?

**Comment by Aappoo69** [comment]
> Are you using a different fuel script?

its just the script from the qbcore, i didnt change it.
