### ISSUE TITLE
Impound

### ISSUE THREAD

**Issue by Epsilona** [JonasDev17/qb-garages#104]
I've got this weird thing whenever a car gets impounded, it dosen't get transfered to the impound garage so there is no way to take out the impounded vehicle.

**Comment by TonybynMp4** [comment]
> I've got this weird thing whenever a car gets impounded, it dosen't get transfered to the impound garage so there is no way to take out the impounded vehicle. 

You either aren't sending it to impound (not our problem) or you're not looking at the impound garage but at the other thing that just lets u take cars that despawned
