### ISSUE TITLE
Car spawning anywhere

### ISSUE THREAD

**Issue by LwkyLion** [JonasDev17/qb-garages#113]
Car spawning anywhere and I turned it off in the config too. in case this helps, it only started happening once I updated the script. so maybe it was something recent that was added? (I'm not sure just trying to help)
![image](https://github.com/JonasDev17/qb-garages/assets/86502614/6d924b0c-bae0-4adc-aad1-02298b9e5c44)
![image](https://github.com/JonasDev17/qb-garages/assets/86502614/6098e8a3-631b-41c2-9450-fe430d17eb3b)
![image](https://github.com/JonasDev17/qb-garages/assets/86502614/07af1f41-54ab-414a-b092-dba170f0e5ec)
I just want to also say, I appreciate you for making this script, just this bug is, well bugging me lol

**Comment by JonasDev17** [comment]
Should be fixed
