### ISSUE TITLE
Garage is not accessible in radialmenu when using radialmenu whilst walking

### ISSUE THREAD

**Issue by W0lv3sxD** [JonasDev17/qb-garages#115]
If Config.UseWhilstWalking in radialmenu is set to true you can not access the garage at all.

**Comment by Log-nx** [comment]
Can confirm I have experienced this as well with this script.

**Comment by JonasDev17** [comment]
Yes its a qb-radialmenu bug

**Comment by JonasDev17** [comment]
This has been fixed
