### ISSUE TITLE
Not in the garage or impound

### ISSUE THREAD

**Issue by eygi** [JonasDev17/qb-garages#121]
if you not parked your car in the garage after the server restart. you cannot locate your car. you cannot see it in the impound or garage. you need to manually change the state in the Sql.

**Comment by RilexBTW** [comment]
I could be wrong, as I'm unsure if this issue has been resolved on my server, but I did notice I stopped getting as many bug reports when I made some changes to qb-policejob. Apparently, there are two types of impound, one where it goes to depot and one where a police officer is required to get the vehicle out. 

My speculation is that the /depot and /impound commands were default to how they are in qb-policejob, and the police officers on my server were going around doing /impound to abandoned cars which was resulting in them being sent to the PD impound, where if they were to use /depot it would send it to depot. I think my solution was to make /impound do the same action as /depot, but I can't remember If I changed anything else.

Try checking out the police impound location while on duty as a police officer and see if the cars are going there. 
You may have changed the coords for the impound location, but by default, they are between Line 31 and 34 in the config.

https://github.com/qbcore-framework/qb-policejob/blob/cc6bf30787b18a235d914d5f84ceecfc22f58095/config.lua#L31-L34

If the vehicles are going there, let me know and I'll look at what changes I made to solve the issue :)
