### ISSUE TITLE
tells me cars aren't at a location after server restart even though showing in database ........

### ISSUE THREAD

**Issue by DopeLovingHippy** [JonasDev17/qb-garages#153]
my issue is after restart cars no longer show in garage you parked at ....... they show again after another restart or restarting garage manually 

<img width="482" alt="11" src="https://github.com/JonasDev17/qb-garages/assets/92433500/de934aba-9d88-46a6-8864-bf8790f475f8">

**Comment by MrTeaRexx** [comment]
I had this problem too, one of the settings brakes the entire script, installing it fix it

**Comment by DopeLovingHippy** [comment]
> I had this problem too, one of the settings brakes the entire script, installing it fix it

any idea which one mate ?

**Comment by MrTeaRexx** [comment]
> > I had this problem too, one of the settings brakes the entire script, installing it fix it
> 
> any idea which one mate ?

Config.StoreParkinglotAccuratly = true
Config.SpawnAtLastParkinglot = true
set them to false

**Comment by JonasDev17** [comment]
> > > I had this problem too, one of the settings brakes the entire script, installing it fix it
> > 
> > 
> > any idea which one mate ?
> 
> Config.StoreParkinglotAccuratly = true Config.SpawnAtLastParkinglot = true set them to false

Did you apply the sql patch? I haven't tried this feature recently so it may be broken but if you do not apply then patch then this feature will definitely not work that's for sure.

**Comment by JonasDev17** [comment]
Nevermind, just saw your bug report. Will take a look at it, thanks
