### ISSUE TITLE
Parking lot setting Issues (bug)

### ISSUE THREAD

**Issue by MrTeaRexx** [JonasDev17/qb-garages#161]
When setting
Config.StoreParkinglotAccuratly = true
Config.SpawnAtLastParkinglot = true 
even with the sql patch1 update this still doesn't work nor does the phone tracking from the readme. when this is turned on it tells the player that their are no vehicles in this location even tho they're actually parked their and storing the vehicles also doesn't work or register. when setting these to true it will get stuck in this state and breaks the script even when setting this back to false.
![20240422215149_1](https://github.com/JonasDev17/qb-garages/assets/55215427/37589637-aff3-4204-b0ce-92e8bd6af3cc)

**Comment by JonasDev17** [comment]
The phonetracking from the readme explicitly says DEPRECATED which means its no longer supported.
