### ISSUE TITLE
Issue with ems/police liveries.

### ISSUE THREAD

**Issue by Leslija** [JonasDev17/qb-garages#62]
I fixed it myself, but it lacks adding livery to the vehicles - EMS and police.
In the original qb garages, it checks if the livery is present and adds it so that the player can take it out with a special livery .

But in this QBCore.Functions.SpawnVehicle(vehicleModel, function(veh) vehicle it is nowhere to be found.

Thank you.

**Comment by ReaPeRz38** [comment]
Hi can you help me to add ems and police livery pls
